FROM nginx:latest

# Change working directory to root of nginx webhost
WORKDIR /usr/share/nginx/html

COPY index.html index.html

# Don't need to specify EXPOSE or CMD because they are in FROM command
