services:
  drupal:
    build:
      context: .
      dockerfile: drupal.Dockerfile 
    image: custom-drupal
    ports:
      - 8080:80
  
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
